/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radiobutton;

import javax.swing.JOptionPane;

/**
 *
 * @author kelvin
 */
public class ex01 extends javax.swing.JFrame {

    /**
     * Creates new form ex01
     */
    public ex01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jcbWin = new javax.swing.JRadioButton();
        jcbAndroid = new javax.swing.JRadioButton();
        jcbIos = new javax.swing.JRadioButton();
        jcbLinux = new javax.swing.JRadioButton();
        jbcConfirma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Qual é o seu sistema operacional?");

        buttonGroup1.add(jcbWin);
        jcbWin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbWin.setText("Windows");
        jcbWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbWinActionPerformed(evt);
            }
        });

        buttonGroup1.add(jcbAndroid);
        jcbAndroid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbAndroid.setText("Android");
        jcbAndroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAndroidActionPerformed(evt);
            }
        });

        buttonGroup1.add(jcbIos);
        jcbIos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbIos.setText("IOS");
        jcbIos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbIosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jcbLinux);
        jcbLinux.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbLinux.setText("Linux");
        jcbLinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLinuxActionPerformed(evt);
            }
        });

        jbcConfirma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbcConfirma.setText("CONFIRMAR");
        jbcConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcConfirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbWin)
                            .addComponent(jcbLinux)
                            .addComponent(jcbIos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbAndroid)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbcConfirma)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jcbWin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbIos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbLinux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbAndroid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbcConfirma)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbWinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbWinActionPerformed

    private void jcbAndroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAndroidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAndroidActionPerformed

    private void jcbIosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbIosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbIosActionPerformed

    private void jcbLinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLinuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbLinuxActionPerformed

    private void jbcConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcConfirmaActionPerformed

        JOptionPane.showMessageDialog(null, "SO selecionada" + GetOpcaoSelecionada());

        // TODO add your handling code here:
    }//GEN-LAST:event_jbcConfirmaActionPerformed
    private String GetOpcaoSelecionada() {
        if (jcbAndroid.isSelected()) {
            return " Android ";
        }
        if (jcbIos.isSelected()) {
            return " IOS ";
        }
        if (jcbLinux.isSelected()) {
            return "Linux";
        }
        if (jcbWin.isSelected()) {
            return " Windows";
        }
        return " ";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbcConfirma;
    private javax.swing.JRadioButton jcbAndroid;
    private javax.swing.JRadioButton jcbIos;
    private javax.swing.JRadioButton jcbLinux;
    private javax.swing.JRadioButton jcbWin;
    // End of variables declaration//GEN-END:variables
}
