
import javax.swing.JOptionPane;
//
//Vamos fazer um aplicativo que permite ao usuário escolher 3 dias da semana para trabalhar em uma ação comunitária. 
//O usuário deve escolher exatamente 3 dias (não mais e nem menos). 
//Para fazer a escolha o usuário terá acesso a um aplicativo com as opções dos dias da semana de segunda a sexta-feira. 
//Caso o usuário tenha escolhido dias a mais ou a dias a menos, será exibida uma mensagem informando isso ao mesmo.
/**
 *
 * @author kelvin
 */
public class AcaoComunitariaGUI extends javax.swing.JFrame {

    
    public AcaoComunitariaGUI() {
        initComponents();
 this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbSegunda = new javax.swing.JCheckBox();
        jcbQuarta = new javax.swing.JCheckBox();
        jcbTerca = new javax.swing.JCheckBox();
        jcbQuinta = new javax.swing.JCheckBox();
        jcbSexta = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro para ação comunitária");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Escolha 3 dias da semana");

        jcbSegunda.setText("Segunda-Feira");

        jcbQuarta.setText("Quarta-Feira");
        jcbQuarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbQuartaActionPerformed(evt);
            }
        });

        jcbTerca.setText("Terca-Feira");
        jcbTerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTercaActionPerformed(evt);
            }
        });

        jcbQuinta.setText("Quinta-Feira");

        jcbSexta.setText("Sexta-feira");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbTerca)
                                .addComponent(jcbSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbQuarta)
                                .addComponent(jcbQuinta)
                                .addComponent(jcbSexta)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbSegunda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbSexta)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTercaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTercaActionPerformed

    private void jcbQuartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbQuartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbQuartaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int quantidaDeDias =0;
       String diasMarcados ="";
       if(jcbSegunda.isSelected()){
           quantidaDeDias++;
           diasMarcados += "Segunda-Feira\n";}
            if(jcbTerca.isSelected()){
           quantidaDeDias++;
           diasMarcados += "terca-Feira\n";
       }  if(jcbQuarta.isSelected()){
           quantidaDeDias++;
           diasMarcados += "Quarta-Feira\n";
       }
         if(jcbQuinta.isSelected()){
           quantidaDeDias++;
           diasMarcados += "Quinta-Feira\n";
       }
           if(jcbSexta.isSelected()){
           quantidaDeDias++;
           diasMarcados += "Sexta-Feira\n";
       }
           
           if(quantidaDeDias<3){
               JOptionPane.showMessageDialog(null,"Você escolheu poucos dias. "
                       + "Deve escolher exatamente 3 dias. ");
               return;
           }
           if(quantidaDeDias>3){
               JOptionPane.showMessageDialog(null,"Você escolheu muitos dias. "
                       + "Deve escolher exatamente 3 dias. ");
        
           return;
           
    }//GEN-LAST:event_jButton1ActionPerformed
JOptionPane.showMessageDialog(null, "você escolheu " + quantidaDeDias+ "dias\n"
        + diasMarcados);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcaoComunitariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcaoComunitariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcaoComunitariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcaoComunitariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcaoComunitariaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jcbQuarta;
    private javax.swing.JCheckBox jcbQuinta;
    private javax.swing.JCheckBox jcbSegunda;
    private javax.swing.JCheckBox jcbSexta;
    private javax.swing.JCheckBox jcbTerca;
    // End of variables declaration//GEN-END:variables
}
