
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kelvin
 */
public class attVictor extends javax.swing.JFrame {

    /**
     * Creates new form attVictor
     */
    public attVictor() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbBoldo = new javax.swing.JCheckBox();
        jcbMentaL = new javax.swing.JCheckBox();
        jcbMentaS = new javax.swing.JCheckBox();
        jcbHortela = new javax.swing.JCheckBox();
        jcbMentaC = new javax.swing.JCheckBox();
        jcbEuca = new javax.swing.JCheckBox();
        jcbUrrito = new javax.swing.JCheckBox();
        jcbPura = new javax.swing.JCheckBox();
        jcbTrad = new javax.swing.JCheckBox();
        jcbSupreme = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jcbTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" ---MEU CARRINHO DE COMPRAS HERBALIZA--- ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Selecione os sabores de sua preferencia");

        jcbBoldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbBoldo.setText("Erva de Terere Boldo e Menta");
        jcbBoldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBoldoActionPerformed(evt);
            }
        });

        jcbMentaL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMentaL.setText("Erva de Terere Menta e Limão");

        jcbMentaS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMentaS.setText("Erva de Terere Menta stronger");

        jcbHortela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbHortela.setText("Erva de Terere Hortelã");

        jcbMentaC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMentaC.setText("Erva de Terere Menta e Cereja");

        jcbEuca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbEuca.setText("Erva de Terere Eucalipto");

        jcbUrrito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbUrrito.setText("Erva dde Terere Burrito");

        jcbPura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbPura.setText("Erva de Terere Pura Folha");

        jcbTrad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbTrad.setText("Erva de Terere Tradicional");

        jcbSupreme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbSupreme.setText("Erva de Terere Supreme Fitx");

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Confirmar Compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcbTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("caixa de observações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbTxt)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbMentaL)
                            .addComponent(jcbBoldo)
                            .addComponent(jcbMentaS)
                            .addComponent(jcbHortela)
                            .addComponent(jcbMentaC)
                            .addComponent(jcbEuca)
                            .addComponent(jcbUrrito)
                            .addComponent(jcbPura)
                            .addComponent(jcbTrad)
                            .addComponent(jcbSupreme)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(jcbBoldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMentaL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMentaS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbHortela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMentaC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbEuca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbUrrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbPura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTrad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbSupreme)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jcbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbBoldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBoldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBoldoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int quantidadeDeErvas = 0;
        String ervasEscolhidas = "";
        
        if (jcbBoldo.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "Boldo e Menta, ";
        }
        if (jcbMentaL.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "Menta e Limão, ";
        }
        if (jcbMentaS.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "Menta Stronger, ";
        }
        if (jcbHortela.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "Hortela, ";
        }
        if (jcbMentaC.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "Menta e Cereja, ";
        }
        if (jcbEuca.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "Eucalipto, ";
        }
        if (jcbPura.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "pura Folha, ";
        }
        if (jcbUrrito.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "Burrito, ";
        }
        if (jcbTrad.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "Tradicional, ";
        }
        if (jcbSupreme.isSelected()) {
            quantidadeDeErvas++;
            ervasEscolhidas += "Supreme fixt,";
        }
          

            if (quantidadeDeErvas > 0) {

                JOptionPane.showMessageDialog(null, "Você escolheu  "  +  quantidadeDeErvas + " ervas"  + ",as ervas escolhidas foram:"
                        + ervasEscolhidas + " essas são as melhores,ótima escolha\n"
                        + jcbTxt.getText() );

                return;
          
            }
            // TODO} add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jcbTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attVictor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attVictor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attVictor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attVictor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attVictor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox jcbBoldo;
    private javax.swing.JCheckBox jcbEuca;
    private javax.swing.JCheckBox jcbHortela;
    private javax.swing.JCheckBox jcbMentaC;
    private javax.swing.JCheckBox jcbMentaL;
    private javax.swing.JCheckBox jcbMentaS;
    private javax.swing.JCheckBox jcbPura;
    private javax.swing.JCheckBox jcbSupreme;
    private javax.swing.JCheckBox jcbTrad;
    private javax.swing.JTextField jcbTxt;
    private javax.swing.JCheckBox jcbUrrito;
    // End of variables declaration//GEN-END:variables
}
