

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kelvin
 */
public class chekbox extends javax.swing.JFrame {

    /**
     * Creates new form chekbox
     */
    public chekbox() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbLendo = new javax.swing.JCheckBox();
        jcbEstudando = new javax.swing.JCheckBox();
        jcbTreinando = new javax.swing.JCheckBox();
        jcbDormindo = new javax.swing.JCheckBox();
        jcbTrabalhando = new javax.swing.JCheckBox();
        jcbAtoa = new javax.swing.JCheckBox();
        jcbFilme = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jlSaida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" o que mais estou fazendo nas horas de folga nessa quarentena");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("você pode marcar mais de uma opção");

        jcbLendo.setText("Lendo");

        jcbEstudando.setText("Estudando");

        jcbTreinando.setText("Treinando");

        jcbDormindo.setText("Dormindo");

        jcbTrabalhando.setText("Trabalhando");

        jcbAtoa.setText("atoa");

        jcbFilme.setText("vendo filme");

        jButton1.setText("confirmar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbEstudando)
                            .addComponent(jcbLendo)
                            .addComponent(jcbTreinando)
                            .addComponent(jcbDormindo)
                            .addComponent(jcbTrabalhando)
                            .addComponent(jcbAtoa)
                            .addComponent(jcbFilme)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel2))))
                .addContainerGap(125, Short.MAX_VALUE))
            .addComponent(jlSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jcbLendo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbEstudando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTreinando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbDormindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTrabalhando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbAtoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbFilme)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jlSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int quantidadeOpcoes = 0;
        String tarefasSelecionadas = "";
        if (jcbLendo.isSelected()) {
            quantidadeOpcoes++;
            tarefasSelecionadas += "Lendo, ";
        }
        if (jcbEstudando.isSelected()) {
            quantidadeOpcoes++;
            tarefasSelecionadas += "Estudando, ";
        }
        if (jcbTreinando.isSelected()) {
            quantidadeOpcoes++;
            tarefasSelecionadas += "Treinando, ";
        } 
        if (jcbDormindo.isSelected()) {
            quantidadeOpcoes++;
            tarefasSelecionadas += "Dormindo, ";
        } 
        if (jcbTrabalhando.isSelected()) {
            quantidadeOpcoes++;
            tarefasSelecionadas += "Trabalhando, ";
        }
        if (jcbFilme.isSelected()) {
            quantidadeOpcoes++;
            tarefasSelecionadas += "Vendo FIlme, ";
        }
        if (jcbAtoa.isSelected()) {
            quantidadeOpcoes++;
            tarefasSelecionadas += "Atoa, ";
                    
        }
        if(tarefasSelecionadas.equals("")){
             jlSaida.setText("Você não selecionou nenhuma alternativa");
             return;
        }
        jlSaida.setText("Você selecionou as seguintes opções "+ quantidadeOpcoes);
        jlSaida.setText(tarefasSelecionadas);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chekbox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chekbox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chekbox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chekbox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chekbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox jcbAtoa;
    private javax.swing.JCheckBox jcbDormindo;
    private javax.swing.JCheckBox jcbEstudando;
    private javax.swing.JCheckBox jcbFilme;
    private javax.swing.JCheckBox jcbLendo;
    private javax.swing.JCheckBox jcbTrabalhando;
    private javax.swing.JCheckBox jcbTreinando;
    private javax.swing.JLabel jlSaida;
    // End of variables declaration//GEN-END:variables
}
